# Configuration file for scheduler-simulator

# This is an example config for scheduler-simulator.

# This is the port number on which kube-scheduler-simulator
# server is started.
Port: 1212

# This is the URL for etcd. The simulator runs kube-apiserver
# internally, and the kube-apiserver uses this etcd.
EtcdURL: "http://simulator-etcd:2379"

# This URL represents the URL once web UI is started.
# The simulator and internal kube-apiserver set the allowed
# origin for CorsAllowedOriginList
CorsAllowedOriginList:
  - "http://localhost:3000"

# This is for the beta feature "Existing cluster Importing".
#  This variable is used to find Kubeconfig required to access your
#  cluster for importing resources to scheduler simulator.
KubeConfig: ""

# This is the host of kube-apiserver which the simulator
# starts internally. Its default value is 127.0.0.1.
KubeApiHost: "127.0.0.1"

# TThis is the port of kube-apiserver. Its default value is 3131.
KubeApiPort: 3131


# The path to a KubeSchedulerConfiguration file.
# If passed, the simulator will start the scheduler
# with that configuration. Or, if you use web UI,
# you can change the configuration from the web UI as well.
KubeSchedulerConfigPath: ""

# This variable indicates whether the simulator will
# import resources from an existing cluster or not.
# Note, this is still a beta feature.
ExternalImportEnabled: false

# This variable indicates whether an external scheduler
# is used.
ExternalSchedulerEnabled: false